print('prashantjha777'.isalnum())
print('prashantjha'.isalpha())
print('777f'.isdigit())
print(''.islower())
print('ksdiuhd'.islower())
print('SURABHI'.isupper())
print('my name is surabhi'.istitle())
print(''.istitle())
print(''.isspace())
print("Hello".startswith("he"))
print("Hello".endswith("lo"))